### ISSUE TITLE
Refresh stories list

### ISSUE THREAD

**Issue by MarcAnt01** [huynhsontung/Indirect#54]
For example if I have seen 4 stories and I go back the unviewed stories, should be first

**Comment by MarcAnt01** [comment]
Checking better the official app I have found out that it doesn't get updated automatically but scrolling down refreshes it

**Comment by huynhsontung** [comment]
Actually there is a secret refresh button for stories. 

![image](https://user-images.githubusercontent.com/31434093/86292239-46338180-bba5-11ea-87a7-0c88e1770624.png)

I have an idea of refreshing the tray when user exit the immersive view (Instagram web behavior). I am personally not a fan of that since I sometimes want to see the stories again right after I close the view. So I am figuring out the UX details to put a refresh button somewhere since pull to refresh is not an option for mouse and keyboard 🤔. Any suggestions?

**Comment by MarcAnt01** [comment]
Hello, I have just seen Instagram PWA and it refreshes the list automatically without the need of a button. That's probably the best UX on Desktop

**Comment by huynhsontung** [comment]
Added a refresh button in 1.2.2
![image](https://user-images.githubusercontent.com/31434093/87252387-768de200-c427-11ea-85e5-3ec7864dda5a.png)
