### ISSUE TITLE
Deleted account

### ISSUE THREAD

**Issue by ramtinak** [huynhsontung/Indirect#55]
Hi,
Thanks for this awesome project you made.
I forked your project and I was going to send u a pull request.
But my instagram account deleted after I tried to login with your app!
`{"message": "Your account has been disabled for violating our terms. Learn how you may be able to restore your account.", "help_url": "https://help.instagram.com/521372114683554", "error_type": "inactive user", "buttons": [{"title": "Appeal", "action": "go_to_helper_url", "helper_url": "https://help.instagram.com/521372114683554"}], "status": "fail"}`

I've checked your code and find out you don't send any requests that instagram is sending while you are in "Sign in" page.
In my library there is 2 functions available for this:
The first one is for requests that you MUST send when your sign in page is navigation to.
https://github.com/ramtinak/InstagramApiSharp/blob/b392c6871cdc99893fc68d1e2ac10d0488781b05/src/InstagramApiSharp/API/InstaApi.cs#L1205-L1229

and the second one, you should send it is for after a success login or loaded session.
https://github.com/ramtinak/InstagramApiSharp/blob/b392c6871cdc99893fc68d1e2ac10d0488781b05/src/InstagramApiSharp/API/InstaApi.cs#L1233-L1252

**Comment by huynhsontung** [comment]
Thank you for the heads up! Also thank you for the amazing work you did in InstagramApiSharp. It helped the development of Indirect tremendously!

Now back to the problem, just to be clear, was it a freshly created account that you used for logging in? I got the same problem while I was creating test accounts too. All my test accounts got deleted minutes after creation even before logging in using Indirect. Since the error message is vague, I suspect this does not have anything to with Indirect.

That being said, it's better to be safe than sorry and adding a few extra requests wouldn't hurt.

**Comment by ramtinak** [comment]
This wasn't your app fault. It's maybe for missing calls.

This was my first instagram account which was made at least 6 years ago maybe it was older i don't know.
