### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by GreenMan36** [huynhsontung/Indirect#78]
I get this: https://i.imgur.com/rOXi0cJ.png
And clicking on send will always close the popup making me unable to use the program since I cannot login.

**Comment by huynhsontung** [comment]
After some testings, I found out that this is due to Instagram's weirdness of not sending the security code at all. It just ends the flow without any error messages whatsoever. 

A way to work around this is to manually log in using their web interface, complete the verification, then try again in Indirect. v1.4.3 added a message that will pop up if this happens. Unless I fully reverse engineer the login challenge flow, which is probably not worth it, I am afraid this is the only solution.

**Comment by GreenMan36** [comment]
I open Indirect, login. Opens the popup that its a suspicious attempt and then I send an email. Email received, window closes.
Can't put the code in there. I open Instagram on the web and say it was me logging in. Try logging in again on Indirect. Back to the start.

Indirect only gives me a message when I use the X that is inside of the Instagram prompt.

Now it's only giving me this: https://i.imgur.com/svhtA5p.png and  I have no clue what you could mean with the "web interface" other than my web browser so... uhhh, help?

**Comment by huynhsontung** [comment]
> I have no clue what you could mean with the "web interface" other than my web browser

Yes, using your web browser, go to https://instagram.com/ and log in from there. It should also prompt you about the suspicious attempt. Once you are done with all the verifications on that side, try again with Indirect. Let me know if it works for you.

**Comment by GreenMan36** [comment]
Nah as I said I did login on the web-browser and it did nothing. The browser in completely separate from Indirect.

**Comment by huynhsontung** [comment]
Sorry I misread that part. Looks like I will have to find a way to reliably replicate this to have a proper solution since my hacky solution doesn't work as well as I expected. I will let you know when a fix is available.

**Comment by GreenMan36** [comment]
Cool, thanks in advance and happy new year!
