### ISSUE TITLE
App crashes after a few seconds

### ISSUE THREAD

**Issue by ValentinWin10** [huynhsontung/Indirect#85]
I've used the app over the last couple of months without any problems but since a couple of days, the app always crashes after a few seconds. New installation of the app does not solve the problem. Do you have any idea for this bug?

**Comment by huynhsontung** [comment]
Does the app crash after all the conversations are loaded or before? Can you open a thread if you click fast enough?

I do indeed see an uptick in crashes with the new version but I have not been able to figure out what is the root cause of it yet.

Edit: I have published an update that may fix some crashing bugs. Let me know if this resolves the problem for you.

**Comment by ValentinWin10** [comment]
Yes, the update fixed the problem! Thank you.
