### ISSUE TITLE
Login worries

### ISSUE THREAD

**Issue by LorisTecnology** [huynhsontung/Indirect#90]
If i log in 
the dev of this program is going to see my log in data?
cause i've seen a strange log in from a device that i don't own

**Comment by huynhsontung** [comment]
When designed this app, I made sure that there is no sensitive information being stored anywhere besides your physical device. There is absolutely no custom logging that logs your data of any kind. The app only collects and I only see:
- Stack trace on exceptions, to help me troubleshoot crashes and other problems.
- Windows version and device name, also for diagnostics purposes.
- How often the app is launched, just to see how well the app is performing.

The strange log-in notice from Instagram is expected as Indirect emulates logging in using an Android device. Note that it is just a mask that Indirect uses to make sure Instagram does not block its access due to the majority of the APIs is mobile-only. There is a small message at the bottom of the login screen that lets you know about this before you login. You can check what device Indirect is emulating by going to the About section in the app menu.

**Comment by LorisTecnology** [comment]
thanks for the answer
so my log in data goes straight to the log in api
cause i've seen this


var api = new InstaApiBuilder()
                .UseLogger(new SomeLogger())
                .UseHttpClient(new SomeHttpClient())
                .SetUser(new UserCredentials(...You user...))
                .UseHttpClient(httpHandlerWithSomeProxy)
                .Build();

and seeing new UserCredentials(...You user...) i've been worried that my log in data will go there in plain text
probably is a misunderstaing

**Comment by huynhsontung** [comment]
The code snippet you referenced does not apply to Indirect anymore. I have modified the Instagram library to some degree so most of the examples like this would not make sense in the context of Indirect. Fundamentally, yes your credential is stored internally in the app as plain text. But since this data is not going anywhere, I don't think it poses a problem. Also, there is no plain text file that stores your credential, the app uses `Windows.Storage.ApplicationData.Current.LocalSettings` to store all of its data.

**Comment by LorisTecnology** [comment]
ok now is clear
thanks a lot
