### ISSUE TITLE
Login should use the default browser, not a WebView frame.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [huynhsontung/Indirect#91]
Having to manually enter my details when I login to Indirect is unnecessary, and makes it harder for me to manage where I am logged-in, since multiple entries shall appear for any device that I use Indirect on.

**Comment by huynhsontung** [comment]
Sorry for the late reply. I have been busy lately.

I personally agree with your comment. But in order for Indirect to use the browser to log in, I will have to set up a server to handle OAuth requests. This significantly adds complexity and might not even work because private messages API might only be available to the official Instagram app. The way Indirect currently works is to construct a login request with the same app ID as the official one and then steals the returned token in the address, which is only possible using a WebView.

**Comment by maialenlolo** [comment]
No me va me pone esto todo el rato.
Se ha producido un error inesperado. Indirect no sabe cómo proceder a continuación y puede bloquearse. Si esto sucede con frecuencia, por favor, envíe un problema en la página de Github de Indirect.

**Comment by RokeJulianLockhart** [comment]
> No me va me pone esto todo el rato.
> Se ha producido un error inesperado. Indirect no sabe cómo proceder a continuación y puede bloquearse. Si esto sucede con frecuencia, por favor, envíe un problema en la página de Github de Indirect.

No debe enviar informes de errores que no sean relevantes para este informe como comentarios de este informe.
